const MESSAGE_TYPES = {
  REQUEST_SENSOR_DATA: 'REQUEST_SENSOR_DATA',
  SENSOR_DATA_RESPONSE: 'SENSOR_DATA_RESPONSE',
  DEVICE_CONNECT: 'DEVICE_CONNECT',
  DEVICE_SETTINGS_UPDATE_ACK: 'DEVICE_SETTINGS_UPDATE_ACK',
  UPDATE_DEVICE_SETTINGS: 'UPDATE_DEVICE_SETTINGS',
  DEVICE_DISCONNECT: 'DEVICE_DISCONNECT',
  PING: 'PING',
  PONG: 'PONG',
};

module.exports = MESSAGE_TYPES;
